// <auto-generated />
namespace WPFChallenge.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CriacaoDoBanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriacaoDoBanco));
        
        string IMigrationMetadata.Id
        {
            get { return "202101291605447_CriacaoDoBanco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
